### ISSUE TITLE
Error with PreciousStones

### ISSUE THREAD

**Issue by xtomyserrax** [marcelo-mason/SimpleClans#571]
Hey, after updating SimpleClans to 2.9.2 Im getting this NoSuchMethodError with the majority of things PreciousStones does (Im using latest PS version). Have you changed something in the API?

https://pastebin.com/Y2WLNhGr

Thanks!

**Comment by RoinujNosde** [comment]
Yes, I removed some methods that were deprecated for using username instead of UUID.

Is PreciousStones' development active?

**Comment by xtomyserrax** [comment]
Ohh I see, could backwards compability be added for that? PS wont be mantained anymore, NathanWolf told me he will just be doing important fixes when minecraft releases new versions but just for making the plugin work, he is not planning on making big fixes or any changes.

He also told me that if someone makes a PR he can accept it though: https://github.com/NathanWolf/PreciousStones/tree/master

**Comment by RoinujNosde** [comment]
I will make a PR then.
But it's not a big fix, PS just need to use getClanPlayer(uuid) instead of getClanPlayer(playerName).

**Comment by xtomyserrax** [comment]
Ohhh okay thanks! PS is an amazing plugin, it could have some improvements but Im not capable of doing them haha (for example preventing destroying protections with WE)

Let me know when you do the PR so I ask the dev on discord to update it! Also, if you want, you can add me to my discord Serra#8975

Thanks for everything!!

**Comment by xtomyserrax** [comment]
Issue fixed! New PS version released: http://jenkins.elmakers.com/job/PreciousStones/25/net.sacredlabyrinth.Phaed$PreciousStones/

Thanks for the PR!

**Comment by RoinujNosde** [comment]
You're welcome
